### ISSUE TITLE
Tablet View NavBar Alignment Issue

### ISSUE THREAD

**Issue by ja03** [GDSC-ASU/website#15]
### Problem

There is a misalignment in the navigation bar when viewed on tablets. The navigation bar items should be horizontally aligned, providing a clear and organized layout for tablet users.

### Solution

To rectify the alignment issue on tablet views, we can fix the width of the sections within the navigation bar. This can be achieved by setting a specific width for each navigation bar item.

**Comment by mbaraa** [comment]
@ja03 
can you provide screenshots of the issue?

**Comment by ja03** [comment]
Sure, here is a screenshot of the issue:
[image: image.png]

And here is the solution:
[image: image.png]

**Comment by ja03** [comment]
Sure, here is a screenshot of the issue:

<img src="https://github.com/GDSC-ASU/website/assets/96989670/ef7720bc-d093-4b13-a0f5-bf3723fd644c" alt="Screenshot of the issue" width="500">

And here is the solution:

<img src="https://github.com/GDSC-ASU/website/assets/96989670/8f2df7d4-de52-468c-84c6-e473e397a23a" alt="Solution" width="500">
